version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: url_shortner
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortner_production